eiai/urls.py
from django.urls import path
from eiai import views

app_name = 'eiai'

urlpatterns = [
    path('', views.index, name='index'),
    path('deck/<slug:deck_name_slug>/', views.show_deck, name='show_deck'),
    path('deck/<slug:deck_name_slug>/daily_extraction', views.daily_extraction, name='daily_extraction'),
    path('about', views.about, name="about"),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

eiai_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from eiai import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('eiai/', include('eiai.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eiai/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django_random_queryset import RandomManager
from django.contrib.auth.models import User


# Create your models here.

class Deck(models.Model):

    name = models.CharField(max_length=50, unique=True)
    description = models.TextField(help_text = "Enter a description", blank=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Deck, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name



class Word(models.Model):

    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name



class Card(models.Model):

    objects = RandomManager()
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='taarot_images', blank=True)
    number = models.IntegerField()
    words = models.ManyToManyField(Word, blank=True)
    description = models.TextField(help_text = "Enter a description", blank=True)

    def __str__(self):
        return self.name



class Address(models.Model):

    address1 = models.CharField(
        "Address line 1",
        max_length=1024,
    )

    address2 = models.CharField(
        "Address line 2",
        max_length=1024,
    )

    zip_code = models.CharField(
        "ZIP / Postal code",
        max_length=12,
    )

    city = models.CharField(
        "City",
        max_length=1024,
    )

    country = models.CharField(
        "Country",
        max_length=30,
    )


    class Meta:
        verbose_name = "Shipping Address"
        verbose_name_plural = "Shipping Addresses"

    def __str__(self):
        return self.address1



class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    addresses = models.ManyToManyField(Address, blank=True)

    def __str__(self):
        return self.user.username
    


class DailyExtraction(models.Model):

    usedDeck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    pickedCards = models.ManyToManyField(Card, blank = True)
    date = models.DateField(auto_now = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

eiai/forms.py
from django import forms 
from django.contrib.auth.models import User
from eiai.models import UserProfile, Address 

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta: 
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')


class AddressForm(forms.ModelForm): 
    
    class Meta:
        model = Address
        fields = ('address1', 'address2', 'city', 'zip_code', 'country')

eiai/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from eiai.models import Deck, Card, UserProfile, Address, DailyExtraction
from eiai.forms import AddressForm, UserForm
import datetime

# Create your views here.

def index(request):

    decks = Deck.objects.order_by('name')
    context_dict = {'boldmessage': 'lettura dei tarocchi per 2 franchi', 'decks': decks}
    return render(request, 'eiai/index.html', context_dict)
    

def show_deck(request, deck_name_slug):
    
    deck = Deck.objects.get(slug=deck_name_slug)
    cards = Card.objects.filter(deck=deck)
    
    context_dict = {'deck': deck, 'cards': cards }
    return render(request, 'eiai/show_deck.html', context_dict)

def about(request):
    
    context_dict = {'hello' : 'welcome to our website!'}
    return render(request, 'eiai/about.html', context_dict)


@login_required
def daily_extraction(request, deck_name_slug):

    try:
        extraction = DailyExtraction.objects.get(user=request.user, date=datetime.date.today())
    except DailyExtraction.DoesNotExist:
        extraction = None
    
    if extraction:
        check = True
    
    else:
        deck = Deck.objects.get(slug=deck_name_slug)
        cards = Card.objects.filter(deck=deck)
        if cards:    
            random_cards = cards.random(3)

        extraction = DailyExtraction()
        extraction.user = request.user
        extraction.usedDeck = deck
        extraction.save()
        extraction.pickedCards.set(random_cards)
        check = False

    context_dict = {'extraction': extraction, 'check': check}
    return render(request, 'eiai/daily_extraction.html', context_dict)


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        address_form = AddressForm(request.POST)
        
        if user_form.is_valid() and address_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            address = address_form.save()
            address.save()
            profile = UserProfile(user=user)
            profile.save()
            profile.addresses.add(address)
            registered = True

        else:
            print(user_form.errors, address_form.errors)
    
    else:
        user_form = UserForm()
        address_form = AddressForm()

    return render(request, 'eiai/register.html', context = {'user_form': user_form, 
                            'address_form': address_form, 'registered': registered})


def user_login(request):
    if request.method == 'POST':
        
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('eiai:index'))
            else:
                return HttpResponse("Your account is disabled")
        else:
            print(f"invakid login details: {username}, {password}")
            return HttpResponse("Invalid login details")

    else:
            return render(request, 'eiai/login.html')

    
@login_required
def user_logout(request):

    logout(request)
    return redirect(reverse('eiai:index'))

templates/eiai/about.html
{% extends 'eiai/base.html' %}
{% load static %}


{% block body_block %}
    <h1>{{ hello }}</h1>

    <div>
        <p>Let's put here all the info</p>
    </div>

{% endblock %}


templates/eiai/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>
        EIAI -
        {% block title_block %}
            Emotional intelligence meets artificial intelligence
        {% endblock %}
    </title>
</head>
<body>
    <div>
        {% block body_block %}
        {% endblock %}
    </div>
    <hr />
    <div>
        <ul>
            <li><a href="{% url 'eiai:about' %}">About</a></li>
            <li><a href="{% url 'eiai:index' %}">Index</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'eiai:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'eiai:login' %}">Login</a></li>
            <li><a href="{% url 'eiai:register' %}">Sign Up</a></li>
            {% endif %}
        </ul>
    </div>

</body> 
</html>

templates/eiai/daily_extraction.html
{% extends 'eiai/base.html' %}
{% load static %}
{% load eiai_template_tags %}

{% block title_block %}
{{ extraction.usedDeck }}
{% endblock %}

{% block body_block %}
    <h1>{{ extraction.usedDeck }}</h1>
    <h3>Daily extraction</h3>

    <div>
        <img src="{% static 'images/hood.jpg' %}" alt="Fatevi leggere il futuro" />
    </div>
    <div>
    {% if check %} 
        <h4>You already had your daily extraction</h4>
    {% else %} 
        <h4>Your daily extraction</h4>
    {% endif %}
        <p>
            {% if extraction.pickedCards %}
                <ul>
                    {% for card in extraction.pickedCards.all %}
                    <li>
                        {{ card }}, <br/>
                        {% get_words card as words %}
                        {% if words %}
                            {% for word in words %}
                                {{ word }}
                            {% endfor %}
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
                {% else %}
                No cards here yet
                {% endif %}
            </p>

    </div>
{% endblock %}

templates/eiai/index.html
{% extends 'eiai/base.html' %}
{% load static %}

{% block body_block %}
    {% if user.is_authenticated %} 
        howdy {{ user.username }}!
    {% else %}
        hey there partner!
    {% endif %}

    <h3>{{ boldmessage }}</h3>

    <div>
        <img src="{% static 'images/hood.jpg' %}" alt="Fatevi leggere il futuro" />
    </div>

    <div>
        <p>
            {% if decks %}
                {% for deck in decks %}
                    <a href="{% url 'eiai:show_deck' deck.slug %}">{{ deck }}</a>
                {% endfor %}
            {% else %}
                No decks yet
            {% endif %}
        </p>
    </div>
{% endblock %}

templates/eiai/login.html
{% extends 'eiai/base.html' %}
{% load static %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<h1>Login to eiai</h1>
<form id="login_form" method="post" action="{% url 'eiai:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50">
    <br />
    Password: <input type="password" name="password" value="" size="50" /> 
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

templates/eiai/register.html
{% extends 'eiai/base.html' %}
{% load static %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}
<h1>Register for Rango</h1>
{% if registered %}
    <strong>Thank you for registering!</strong>
    <a href="{% url 'eiai:index' %}">Return to the homepage.</a><br/>
{% else %}
    Rango says: <strong>Register here!</strong><br/>
    <form id="user_form" method="post" action="{% url 'eiai:register' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }} 
        {{ address_form.as_p }}
        <input type="submit" name="submit" value="Register" /> 
    </form>
{% endif %} 
{% endblock %}

templates/eiai/show_deck.html
{% extends 'eiai/base.html' %}
{% load static %}


{% block title_block %}
    {{ deck.name }}
{% endblock %}

{% block body_block %}
    <h1>{{ deck.name }}</h1>

    <div>
        <img src="{% static 'images/hood.jpg' %}" alt="Fatevi leggere il futuro" />
        <a href="{% url 'eiai:daily_extraction' deck.slug %}">Do your daily extraction!</a>
    </div>

    <div>
        <p>
            {{ deck.description }}
            <br />
            <hr />
            {% if cards %}
            <ul>
                {% for card in cards %}
                    <li>{{ card }}</li>
                {% endfor %}
            </ul>
            {% else %}
                No cards here yet
            {% endif %}
        </p>
    </div>
{% endblock %}